# Generated by Django 5.2.7 on 2025-10-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tast',
            new_name='Task',
        ),
    ]
